name: MATLAB Tests
on: 
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: [self-hosted, matlab]
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        /usr/local/MATLAB/R2020a/bin/matlab -batch "runtests('test/testAll.m')"
